"""Proposing review rules for a repository: generated by a model, or imported
from the convention files the repository already has.

    generate_rules(ws, repo_slug, actor)  — read the repository (its vault
        notes when it has been documented, a sample of its files from the
        clone either way), ask the workspace's review model once — twice when
        the first reply cannot be read — for rules that fit THIS codebase,
        and write them as PENDING proposals (origin "generated") with the
        model's rationale and examples.
    import_rules(ws, repo_slug, actor)    — no model at all: read CONTRIBUTING,
        CLAUDE.md, AGENTS.md, Cursor / Copilot instructions, .editorconfig and
        the ESLint / PHPCS / Ruff configs from the clone, turn each normative
        section or config into a rule, and write them as PENDING proposals
        (origin "imported", `source_ref` = the file and section).

Nothing either of them writes reaches a review until a person approves it.

Both run as a background job (`review_rule_jobs`): `start_job` records it,
`run_job` executes it and leaves the outcome on the row the page polls. A job
row still "running" long after anything could be working on it (the API
restarted under it) reads back as failed rather than spinning forever.

The model call goes through the workspace's REVIEW profile and is booked on
its own line of the bill — spend surface and operation "rules_generate" — so
"what did rule generation cost" is a question the Usage page can answer.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import subprocess
from collections import Counter
from collections.abc import Callable
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

#: The spend surface and ledger operation the model call is booked under —
#: the same word, `src.llm.budget.SURFACE_RULES_GENERATE`.
RULES_GENERATE_OPERATION = "rules_generate"

DEFAULT_COUNT = 8
MAX_COUNT = 20
#: Characters of repository evidence handed to the model (≈ 8k tokens).
DIGEST_BUDGET_CHARS = 32_000
PER_FILE_CHARS = 2_400
SAMPLE_FILES = 14
VAULT_CHARS = 6_000
MAX_OUTPUT_TOKENS = 8_000
LLM_TIMEOUT_SECONDS = 180.0

#: Imported proposals per run, and per file.
MAX_IMPORTED = 40
MAX_PER_FILE = 15

#: A job not touched for this long is not running any more.
STALE_AFTER = timedelta(minutes=30)

JOB_KINDS = ("generate", "import")

_SKIP_DIRS = frozenset({
    ".git", "node_modules", "vendor", "dist", "build", ".next", ".venv", "venv",
    "__pycache__", ".tox", ".mypy_cache", ".pytest_cache", "coverage",
    "target", ".idea", ".vscode", "bower_components", ".gradle",
})
_SOURCE_EXT = {
    ".py": "python", ".js": "javascript", ".jsx": "javascript",
    ".mjs": "javascript", ".cjs": "javascript", ".ts": "typescript",
    ".tsx": "typescript", ".vue": "vue", ".php": "php", ".sql": "sql",
    ".go": "go", ".rb": "ruby", ".java": "java", ".kt": "kotlin",
    ".cs": "csharp", ".rs": "rust", ".swift": "swift", ".scala": "scala",
    ".c": "c", ".h": "c", ".cpp": "cpp", ".hpp": "cpp", ".svelte": "svelte",
}
_GENERATED_HINTS = (".min.", ".lock", "generated", "migrations/versions")


class RulesJobError(RuntimeError):
    """A job that cannot run, said in a sentence a person can act on."""


def _actor_email(actor: Any) -> str | None:
    if actor is None:
        return None
    if isinstance(actor, str):
        return actor or None
    return getattr(actor, "email", None) or getattr(actor, "id", None)


def _actor_id(actor: Any) -> str:
    if actor is None or isinstance(actor, str):
        return "system"
    return str(getattr(actor, "user_id", None) or getattr(actor, "id", None) or "system")


def repo_root(repo_slug: str) -> Path | None:
    """The repository's clone, or None when there is none."""
    from src.config import get_settings

    try:
        path = get_settings().repo_path(repo_slug)
    except Exception:  # noqa: BLE001 — an invalid slug has no clone
        return None
    return path if path.is_dir() else None


# ─── Reading the repository ──────────────────────────────────────────


def list_files(root: Path, *, cap: int = 5000) -> list[str]:
    """Repository-relative paths: what git tracks, else a walk that skips
    dependency and build directories."""
    try:
        run = subprocess.run(
            ["git", "-C", str(root), "ls-files"],
            capture_output=True, text=True, timeout=20, check=True,
        )
        tracked = [ln.strip() for ln in run.stdout.splitlines() if ln.strip()]
        if tracked:
            return [f for f in tracked
                    if not any(part in _SKIP_DIRS for part in f.split("/")[:-1])][:cap]
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        pass
    out: list[str] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        for name in sorted(filenames):
            rel = os.path.relpath(os.path.join(dirpath, name), root)
            out.append(rel.replace(os.sep, "/"))
            if len(out) >= cap:
                return out
    return out


def _language_stats(files: list[str]) -> Counter:
    return Counter(
        _SOURCE_EXT[Path(f).suffix.lower()] for f in files
        if Path(f).suffix.lower() in _SOURCE_EXT
    )


def _sample_sources(root: Path, files: list[str], languages: Counter,
                    cap: int = SAMPLE_FILES) -> list[str]:
    """A spread of ordinary source files of the repository's main languages:
    not tests first, not generated, not tiny, not huge; spread over
    directories so one package does not stand for the codebase."""
    top = [lang for lang, _ in languages.most_common(3)]
    candidates: list[tuple[int, str]] = []
    for f in files:
        lang = _SOURCE_EXT.get(Path(f).suffix.lower())
        if lang not in top:
            continue
        low = f.lower()
        if any(h in low for h in _GENERATED_HINTS):
            continue
        try:
            size = (root / f).stat().st_size
        except OSError:
            continue
        if size < 300 or size > 60_000:
            continue
        is_test = "test" in low or "spec" in low
        candidates.append((1 if is_test else 0, f))
    candidates.sort()
    picked: list[str] = []
    seen_dirs: Counter = Counter()
    for _, f in candidates:
        parent = f.rsplit("/", 1)[0] if "/" in f else ""
        if seen_dirs[parent] >= 2:
            continue
        seen_dirs[parent] += 1
        picked.append(f)
        if len(picked) >= cap:
            break
    return picked


def _vault_excerpt(repo_slug: str, budget: int = VAULT_CHARS) -> tuple[str, int]:
    """The repository's generated documentation (vault notes), overview
    first — what indexing already learned about it. ("", 0) without one."""
    from src.config import get_settings

    try:
        vault = get_settings().repo_vault_path(repo_slug)
    except Exception:  # noqa: BLE001
        return "", 0
    if not vault.is_dir():
        return "", 0
    notes = sorted(vault.rglob("*.md"))
    if not notes:
        return "", 0

    def rank(p: Path) -> tuple[int, str]:
        name = p.name.lower()
        first = any(k in name for k in ("overview", "readme", "index", "architecture"))
        return (0 if first else 1, str(p))

    parts: list[str] = []
    left = budget
    for note in sorted(notes, key=rank)[:6]:
        try:
            text = note.read_text(encoding="utf-8", errors="replace").strip()
        except OSError:
            continue
        take = text[: min(len(text), max(0, left), 2_000)]
        if not take:
            break
        parts.append(f"### {note.relative_to(vault)}\n{take}")
        left -= len(take)
        if left <= 0:
            break
    return "\n\n".join(parts), len(notes)


def build_repo_digest(repo_slug: str, root: Path | None = None) -> tuple[str, dict]:
    """(evidence text for the model, stats). Raises RulesJobError when there
    is nothing to read."""
    root = root or repo_root(repo_slug)
    vault_text, vault_notes = _vault_excerpt(repo_slug)
    files = list_files(root) if root else []
    if not files and not vault_text:
        raise RulesJobError(
            "This repository has no clone and no documentation to read yet — "
            "index it on the Repositories page first.")
    languages = _language_stats(files)
    sections = [f"# Repository: {repo_slug}"]
    if languages:
        sections.append("## Languages (source files)\n" + ", ".join(
            f"{lang} {n}" for lang, n in languages.most_common(8)))
    if vault_text:
        sections.append("## Documentation already generated for it\n" + vault_text)
    if files:
        tree = "\n".join(f"- {f}" for f in files[:150])
        more = f"\n- … and {len(files) - 150} more" if len(files) > 150 else ""
        sections.append(f"## Files ({len(files)})\n{tree}{more}")
    sampled: list[str] = []
    if root and files:
        budget = DIGEST_BUDGET_CHARS - sum(len(s) for s in sections)
        for f in _sample_sources(root, files, languages):
            if budget <= 500:
                break
            try:
                text = (root / f).read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            take = text[: min(PER_FILE_CHARS, budget)]
            sections.append(f"### `{f}`\n```\n{take}\n```")
            budget -= len(take) + len(f) + 16
            sampled.append(f)
    stats = {"files": len(files), "sampled": sampled, "vault_notes": vault_notes,
             "languages": dict(languages.most_common(8))}
    return "\n\n".join(sections)[:DIGEST_BUDGET_CHARS + 4_000], stats


# ─── Generating ──────────────────────────────────────────────────────

_SYSTEM = """You write code review rules for ONE repository, from evidence about it.

A good rule is specific to this codebase: it names its conventions, its frameworks, its \
failure modes, the mistakes its code invites. Generic advice ("write clean code", \
"add comments") is useless — skip it. Every rule must be checkable on a diff by a \
reviewer who reads only the changed lines and the rule.

Reply with ONE JSON object and nothing around it:
{"rules": [
  {"title": "<imperative, at most 90 characters, unique>",
   "instructions": "<what to flag and what is acceptable, at most 1200 characters>",
   "severity": "info" | "warning" | "error" | "critical",
   "path_glob": "<glob of the files it applies to, e.g. src/**/*.py or *.{ts,tsx}; empty for all files>",
   "rationale": "<one or two sentences: the evidence in THIS repository that makes the rule worth having>",
   "examples_good": "<a short compliant snippet in the repository's style>",
   "examples_bad": "<a short violating snippet>"}
]}"""


def _prompt(count: int, existing_titles: list[str]) -> str:
    lines = [f"Propose up to {count} review rules for the repository described in the "
             "code context."]
    if existing_titles:
        lines.append("It already has these rules — do not repeat or rephrase them:")
        lines += [f"- {t}" for t in existing_titles[:80]]
    lines.append("Reply with the JSON object only.")
    return "\n".join(lines)


def parse_rules_reply(text: str) -> list[dict] | None:
    """The `rules` list of a model reply, or None when it cannot be read.
    Accepts a bare list, an object with `rules`, and fenced JSON."""
    raw = (text or "").strip()
    if not raw:
        return None
    candidates: list[str] = []
    fences = re.findall(r"```(?:json)?\s*(.*?)```", raw, re.S)
    candidates += list(reversed(fences))
    for opener, closer in (("{", "}"), ("[", "]")):
        start, end = raw.find(opener), raw.rfind(closer)
        if start != -1 and end > start:
            candidates.append(raw[start:end + 1])
    candidates.append(raw)
    for c in candidates:
        try:
            obj = json.loads(c)
        except (json.JSONDecodeError, TypeError):
            continue
        if isinstance(obj, dict):
            obj = obj.get("rules")
        if isinstance(obj, list):
            return [r for r in obj if isinstance(r, dict)]
    return None


def _clean_generated(rule: dict) -> dict:
    """Coerce a model's rule into the store's field names and limits; the
    store's validator decides the rest."""
    def s(key: str, limit: int) -> str | None:
        value = rule.get(key)
        if value is None:
            return None
        if isinstance(value, list):
            value = ", ".join(str(v) for v in value)
        text = str(value).strip()
        return text[:limit] if text else None

    severity = str(rule.get("severity") or "warning").strip().lower()
    if severity not in ("info", "warning", "error", "critical"):
        severity = "warning"
    return {
        "title": s("title", 200),
        "instructions": s("instructions", 2000),
        "severity": severity,
        "path_glob": s("path_glob", 500),
        "rationale": s("rationale", 2000),
        "examples_good": s("examples_good", 2000),
        "examples_bad": s("examples_bad", 2000),
        "agents": [],
    }


def _llm_client(ws: str, actor: Any) -> Any:
    """The workspace's review route, booked as rules_generate."""
    from src.llm.budget import SURFACE_RULES_GENERATE
    from src.llm.client import build_llm_client

    def _model(_agent: str | None = None) -> str | None:
        try:
            from src.llm.profiles import resolve_profile

            return resolve_profile("review", ws).model
        except Exception:  # noqa: BLE001
            return None

    return build_llm_client(_actor_id(actor), ws, surface="review",
                            spend_surface=SURFACE_RULES_GENERATE,
                            resolve_model=_model)


async def generate_rules(
    ws: str,
    repo_slug: str,
    actor: Any,
    *,
    count: int = DEFAULT_COUNT,
    llm: Any = None,
    progress: Callable[[str], Any] | None = None,
) -> dict[str, Any]:
    """Propose rules for `repo_slug` as pending, origin "generated".

    Returns {"created": [ids], "proposed": n, "skipped": n, "context": stats}.
    Raises RulesJobError for an outcome a person must act on (no clone, a
    reply that could not be read twice, the model call failing).
    """
    from src.review.rules_store import list_rules, propose_rules

    count = max(1, min(MAX_COUNT, int(count or DEFAULT_COUNT)))
    await _say(progress, "Reading the repository")
    digest, stats = await asyncio.to_thread(build_repo_digest, repo_slug)

    existing = await list_rules(ws)
    titles = [r["title"] for r in existing
              if r["repo_slug"] in (None, repo_slug)]

    client = llm if llm is not None else await asyncio.to_thread(_llm_client, ws, actor)
    await _say(progress, "Asking the model")
    prompt = _prompt(count, titles)
    rules: list[dict] | None = None
    reply_text = ""
    for attempt in range(2):
        try:
            result = await asyncio.to_thread(
                client.generate,
                prompt=prompt if attempt == 0 else (
                    prompt + "\n\nYour previous reply could not be parsed as JSON. "
                    "Reply with the JSON object only, no prose, no code fences."),
                code_context=digest,
                system_instruction=_SYSTEM,
                agent="rules_generate",
                mode="review",
                operation=RULES_GENERATE_OPERATION,
                repo=repo_slug,
                temperature=0.2,
                max_output_tokens=MAX_OUTPUT_TOKENS,
                num_retries=1,
                timeout=LLM_TIMEOUT_SECONDS,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning("rules_generate_llm_failed ws=%s repo=%s err=%s",
                           ws, repo_slug, str(exc)[:300])
            raise RulesJobError(_failure_sentence(exc)) from exc
        reply_text = getattr(result, "text", "") or ""
        rules = parse_rules_reply(reply_text)
        if rules is not None:
            break
    if rules is None:
        logger.warning("rules_generate_unreadable ws=%s repo=%s chars=%d",
                       ws, repo_slug, len(reply_text))
        raise RulesJobError("The model's reply could not be read as rules, twice. "
                            "Try again, or choose another review model.")

    await _say(progress, "Saving the proposals")
    cleaned = [_clean_generated(r) for r in rules[:count]]
    for rule in cleaned:
        rule["source_ref"] = "generated"
    ids = await propose_rules(ws, repo_slug, cleaned, "generated",
                              _actor_email(actor), skip_invalid=True)
    return {"created": ids, "proposed": len(cleaned),
            "skipped": len(cleaned) - len(ids), "context": stats}


def _failure_sentence(exc: BaseException) -> str:
    try:
        from src.llm.errors import classify, curated_reason

        reason = curated_reason(classify(exc).code)
        if reason:
            return reason
    except Exception:  # noqa: BLE001
        pass
    return f"The model call failed ({type(exc).__name__})."


async def _say(progress: Callable[[str], Any] | None, text: str) -> None:
    if progress is None:
        return
    out = progress(text)
    if asyncio.iscoroutine(out):
        await out


# ─── Importing convention files ──────────────────────────────────────

#: Markdown instruction files, by path from the repository root.
MARKDOWN_FILES: tuple[str, ...] = (
    "CONTRIBUTING.md", ".github/CONTRIBUTING.md", "docs/CONTRIBUTING.md",
    "CLAUDE.md", ".claude/CLAUDE.md", "AGENTS.md",
    ".github/copilot-instructions.md", ".cursorrules",
)
CURSOR_RULES_DIR = ".cursor/rules"
EDITORCONFIG = ".editorconfig"
ESLINT_FILES: tuple[str, ...] = (
    ".eslintrc", ".eslintrc.json", ".eslintrc.js", ".eslintrc.cjs",
    ".eslintrc.yml", ".eslintrc.yaml", "eslint.config.js", "eslint.config.mjs",
    "eslint.config.cjs", "eslint.config.ts",
)
PHPCS_FILES: tuple[str, ...] = (
    "phpcs.xml", "phpcs.xml.dist", ".phpcs.xml", ".phpcs.xml.dist",
)
RUFF_FILES: tuple[str, ...] = ("ruff.toml", ".ruff.toml", "pyproject.toml")

_NORMATIVE = re.compile(
    r"\b(must|should|never|always|do not|don't|avoid|prefer|required?|ensure|"
    r"use|make sure|no\s+\w+)\b", re.I)
_SKIP_SECTIONS = re.compile(
    r"^(table of contents|contents|toc|license|licence|code of conduct|"
    r"acknowledg\w*|credits|changelog|getting started|installation|install|"
    r"setup|quick ?start|support|contact|links|reporting a security issue)$", re.I)
_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
_JS_GLOB = "*.{js,jsx,mjs,cjs,ts,tsx,vue}"


def _clip(text: str, limit: int = 2000) -> str:
    text = text.strip()
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60]


def _clean_heading(text: str) -> str:
    text = re.sub(r"[`*_~]", "", text)
    text = re.sub(r"[^\w\s\-/&.,:()'+#]", "", text)
    return " ".join(text.split()).strip(" :-")


def markdown_sections(text: str) -> list[tuple[str, str]]:
    """[(heading, body)] of a markdown document; a document with no heading
    is one section with an empty heading. Fenced code is not scanned for
    headings."""
    sections: list[tuple[str, list[str]]] = [("", [])]
    in_fence = False
    for line in text.splitlines():
        if line.strip().startswith("```"):
            in_fence = not in_fence
        m = None if in_fence else _HEADING.match(line)
        if m:
            sections.append((_clean_heading(m.group(2)), []))
        else:
            sections[-1][1].append(line)
    return [(h, "\n".join(body).strip()) for h, body in sections]


def _markdown_rules(rel: str, text: str) -> list[dict]:
    out: list[dict] = []
    stem = Path(rel).name
    for heading, body in markdown_sections(text):
        if len(body) < 40 or (heading and _SKIP_SECTIONS.match(heading)):
            continue
        if not _NORMATIVE.search(body) and not re.search(r"^\s*[-*]\s", body, re.M):
            continue
        title = heading or f"Conventions from {stem}"
        out.append({
            "title": _clip(title, 200),
            "instructions": _clip(body),
            "severity": "warning",
            "source_ref": f"{rel}#{_slug(heading)}" if heading else rel,
        })
        if len(out) >= MAX_PER_FILE:
            break
    return out


def _frontmatter(text: str) -> tuple[dict[str, str], str]:
    """(simple `key: value` frontmatter, body) of an .mdc file."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end < 0:
        return {}, text
    meta: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip().lower()] = v.strip().strip("\"'")
    return meta, text[end + 4:].lstrip("\n")


def _cursor_rule(rel: str, text: str) -> list[dict]:
    meta, body = _frontmatter(text)
    if len(body.strip()) < 20:
        return []
    globs = meta.get("globs", "")
    globs = ", ".join(g.strip().strip("\"'") for g in globs.strip("[]").split(",") if g.strip())
    title = meta.get("description") or Path(rel).stem.replace("-", " ").replace("_", " ")
    return [{
        "title": _clip(title[:1].upper() + title[1:], 200),
        "instructions": _clip(body),
        "path_glob": globs or None,
        "severity": "warning",
        "source_ref": rel,
    }]


def _editorconfig_rules(rel: str, text: str) -> list[dict]:
    out: list[dict] = []
    section = None
    props: dict[str, list[str]] = {}
    order: list[str] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", ";")):
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1].strip()
            if section not in props:
                props[section] = []
                order.append(section)
            continue
        if section is None or "=" not in line:
            continue
        k, v = (p.strip() for p in line.split("=", 1))
        if k.lower() == "root":
            continue
        props[section].append(f"{k} = {v}")
    for section in order:
        if not props[section]:
            continue
        glob = None if section in ("*", "**") else section
        out.append({
            "title": _clip(f"Formatting for {section}" if glob else "Formatting for every file", 200),
            "instructions": _clip(
                "Follow the repository's .editorconfig for "
                f"{'`' + section + '`' if glob else 'every file'}: "
                + "; ".join(props[section])
                + ". Flag changed lines that break these settings (indentation, "
                  "line endings, trailing whitespace, final newline, charset)."),
            "path_glob": glob,
            "severity": "info",
            "source_ref": f"{rel}#{_slug(section) or 'all'}",
        })
    return out[:MAX_PER_FILE]


def _eslint_rule(rel: str, text: str) -> list[dict]:
    configured: list[str] = []
    extends: list[str] = []
    data = None
    if rel.endswith((".json", "rc")):
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            data = None
    if isinstance(data, dict):
        for name, level in (data.get("rules") or {}).items():
            lvl = level[0] if isinstance(level, list) and level else level
            if str(lvl) not in ("off", "0"):
                configured.append(f"{name} ({lvl})")
        ext = data.get("extends") or []
        extends = [ext] if isinstance(ext, str) else [str(e) for e in ext]
    else:
        for name, lvl in re.findall(
                r"""['"]([@\w/-]+)['"]\s*:\s*\[?\s*['"]?(error|warn|2|1)['"]?""", text):
            configured.append(f"{name} ({lvl})")
        extends = re.findall(r"""extends\s*:\s*\[?\s*['"]([^'"]+)['"]""", text)
    if not configured and not extends:
        return []
    parts = ["This repository lints JavaScript/TypeScript with ESLint "
             f"(`{rel}`). Flag changed code that the configuration would reject"]
    if extends:
        parts.append(f"; it extends {', '.join(dict.fromkeys(extends))}")
    if configured:
        parts.append(". Configured rules: " + ", ".join(configured[:60]))
    return [{
        "title": "Follow the ESLint configuration",
        "instructions": _clip("".join(parts) + "."),
        "path_glob": _JS_GLOB,
        "severity": "warning",
        "source_ref": rel,
    }]


def _phpcs_rule(rel: str, text: str) -> list[dict]:
    refs = re.findall(r"""<rule\s+ref\s*=\s*["']([^"']+)["']""", text)
    if not refs:
        return []
    return [{
        "title": "Follow the PHP_CodeSniffer standard",
        "instructions": _clip(
            f"This repository checks PHP with PHP_CodeSniffer (`{rel}`). Flag "
            "changed PHP code that violates the configured standards and sniffs: "
            + ", ".join(dict.fromkeys(refs)) + "."),
        "path_glob": "*.php",
        "severity": "warning",
        "source_ref": rel,
    }]


def _ruff_rule(rel: str, text: str) -> list[dict]:
    import tomllib

    try:
        data = tomllib.loads(text)
    except (tomllib.TOMLDecodeError, ValueError):
        return []
    cfg = data.get("tool", {}).get("ruff") if rel.endswith("pyproject.toml") else data
    if not isinstance(cfg, dict) or not cfg:
        return []
    lint = cfg.get("lint") if isinstance(cfg.get("lint"), dict) else {}
    facts: list[str] = []
    for key in ("line-length", "target-version"):
        if key in cfg:
            facts.append(f"{key} = {cfg[key]}")
    for key in ("select", "extend-select", "ignore"):
        value = lint.get(key, cfg.get(key))
        if value:
            facts.append(f"{key} = {', '.join(map(str, value))}")
    if not facts:
        facts.append("the default rule set")
    return [{
        "title": "Follow the Ruff configuration",
        "instructions": _clip(
            f"This repository lints Python with Ruff (`{rel}`): " + "; ".join(facts)
            + ". Flag changed Python code that this configuration would reject."),
        "path_glob": "*.py",
        "severity": "info",
        "source_ref": rel,
    }]


def scan_convention_files(root: Path) -> list[dict]:
    """Proposals read from the repository's convention files, in a stable
    order. Pure: reads files, writes nothing."""
    def read(rel: str) -> str | None:
        path = root / rel
        try:
            if path.is_file() and path.stat().st_size <= 400_000:
                return path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return None
        return None

    found: list[dict] = []
    for rel in MARKDOWN_FILES:
        text = read(rel)
        if text:
            found += _markdown_rules(rel, text)
    cursor_dir = root / CURSOR_RULES_DIR
    if cursor_dir.is_dir():
        for path in sorted(cursor_dir.iterdir()):
            if path.suffix.lower() in (".mdc", ".md"):
                rel = f"{CURSOR_RULES_DIR}/{path.name}"
                text = read(rel)
                if text:
                    found += _cursor_rule(rel, text)
    text = read(EDITORCONFIG)
    if text:
        found += _editorconfig_rules(EDITORCONFIG, text)
    for rel in ESLINT_FILES:
        text = read(rel)
        if text:
            found += _eslint_rule(rel, text)
            break
    for rel in PHPCS_FILES:
        text = read(rel)
        if text:
            found += _phpcs_rule(rel, text)
            break
    for rel in RUFF_FILES:
        text = read(rel)
        if text:
            got = _ruff_rule(rel, text)
            if got:
                found += got
                break

    # Two files with a "Testing" section: the second keeps its file name.
    seen: set[str] = set()
    out: list[dict] = []
    for rule in found:
        key = rule["title"].casefold()
        if key in seen:
            src = rule["source_ref"].split("#", 1)[0]
            rule["title"] = _clip(f"{rule['title']} ({Path(src).name})", 200)
            key = rule["title"].casefold()
            if key in seen:
                continue
        seen.add(key)
        out.append(rule)
    return out[:MAX_IMPORTED]


async def import_rules(
    ws: str,
    repo_slug: str,
    actor: Any,
    *,
    root: Path | None = None,
    progress: Callable[[str], Any] | None = None,
) -> dict[str, Any]:
    """Propose the repository's own conventions as pending rules (origin
    "imported"). Re-running proposes only what is new: a title the
    repository already has — approved, pending or rejected — is skipped."""
    from src.review.rules_store import propose_rules

    root = root or repo_root(repo_slug)
    if root is None:
        raise RulesJobError(
            "This repository has no clone to read yet — index it on the "
            "Repositories page first.")
    await _say(progress, "Reading convention files")
    found = await asyncio.to_thread(scan_convention_files, root)
    files = sorted({r["source_ref"].split("#", 1)[0] for r in found})
    for rule in found:
        rule.setdefault("agents", [])
    await _say(progress, "Saving the proposals")
    ids = await propose_rules(ws, repo_slug, found, "imported", _actor_email(actor),
                              skip_invalid=True) if found else []
    return {"created": ids, "proposed": len(found), "skipped": len(found) - len(ids),
            "files": files}


# ─── Jobs ────────────────────────────────────────────────────────────


def _aware(value: datetime | None) -> datetime | None:
    if value is None:
        return None
    return value if value.tzinfo is not None else value.replace(tzinfo=UTC)


def job_to_dict(row: Any) -> dict[str, Any]:
    status = row.status
    error = row.error
    touched = _aware(row.updated_at) or _aware(row.created_at)
    if status in ("queued", "running") and touched is not None \
            and datetime.now(UTC) - touched > STALE_AFTER:
        status = "failed"
        error = error or "The job was interrupted (the server restarted). Start it again."
    return {
        "id": row.id,
        "repo_slug": row.repo_slug,
        "kind": row.kind,
        "status": status,
        "progress": row.progress or "",
        "result": dict(row.result or {}),
        "error": error or "",
        "created_by": row.created_by,
        "created_at": _aware(row.created_at).isoformat() if row.created_at else None,
        "finished_at": _aware(row.finished_at).isoformat() if row.finished_at else None,
    }


async def start_job(ws: str, repo_slug: str, kind: str, actor: Any) -> tuple[dict, bool]:
    """(the job, created?) — an unfinished job of the same kind for the same
    repository is returned instead of starting a second one."""
    from sqlalchemy import select

    from src.db.models import ReviewRuleJob
    from src.db.session import async_session

    if kind not in JOB_KINDS:
        raise ValueError(f"unknown job kind {kind!r}")
    async with async_session() as s:
        live = (await s.scalars(select(ReviewRuleJob).where(
            ReviewRuleJob.workspace_id == ws, ReviewRuleJob.repo_slug == repo_slug,
            ReviewRuleJob.kind == kind,
            ReviewRuleJob.status.in_(("queued", "running")),
        ).order_by(ReviewRuleJob.created_at.desc()))).first()
        if live is not None:
            current = job_to_dict(live)
            if current["status"] != "failed":
                return current, False
        row = ReviewRuleJob(workspace_id=ws, repo_slug=repo_slug, kind=kind,
                            status="queued", progress="Queued",
                            created_by=_actor_email(actor))
        s.add(row)
        await s.commit()
        await s.refresh(row)
        return job_to_dict(row), True


async def _update_job(job_id: str, **fields: Any) -> None:
    from src.db.models import ReviewRuleJob
    from src.db.session import async_session

    async with async_session() as s:
        row = await s.get(ReviewRuleJob, job_id)
        if row is None:
            return
        for key, value in fields.items():
            setattr(row, key, value)
        row.updated_at = datetime.now(UTC)
        await s.commit()


async def run_job(job_id: str, actor: Any = None, *, llm: Any = None) -> dict | None:
    """Execute a queued job and record its outcome. Never raises."""
    from src.db.models import ReviewRuleJob
    from src.db.session import async_session

    async with async_session() as s:
        row = await s.get(ReviewRuleJob, job_id)
        if row is None:
            return None
        ws, repo_slug, kind = row.workspace_id, row.repo_slug, row.kind
        actor = actor if actor is not None else row.created_by

    async def progress(text: str) -> None:
        await _update_job(job_id, progress=text)

    await _update_job(job_id, status="running", progress="Starting")
    try:
        if kind == "generate":
            result = await generate_rules(ws, repo_slug, actor, llm=llm, progress=progress)
        else:
            result = await import_rules(ws, repo_slug, actor, progress=progress)
    except RulesJobError as exc:
        await _update_job(job_id, status="failed", error=str(exc)[:1000],
                          progress="", finished_at=datetime.now(UTC))
        return None
    except Exception as exc:  # noqa: BLE001
        logger.exception("review_rules_job_failed id=%s kind=%s", job_id, kind)
        await _update_job(job_id, status="failed",
                          error=f"The job failed ({type(exc).__name__}).",
                          progress="", finished_at=datetime.now(UTC))
        return None
    await _update_job(job_id, status="completed", progress="Done",
                      result=json.loads(json.dumps(result, default=str)),
                      finished_at=datetime.now(UTC))
    logger.info("review_rules_job_done id=%s kind=%s ws=%s repo=%s created=%d",
                job_id, kind, ws, repo_slug, len(result.get("created") or []))
    return result


async def get_job(ws: str, job_id: str) -> dict | None:
    """One job of `ws`, or None (another workspace's job is None too)."""
    from src.db.models import ReviewRuleJob
    from src.db.session import async_session

    async with async_session() as s:
        row = await s.get(ReviewRuleJob, job_id)
        if row is None or row.workspace_id != ws:
            return None
        return job_to_dict(row)


async def list_jobs(ws: str, repo_slug: str | None = None, *, limit: int = 10) -> list[dict]:
    from sqlalchemy import select

    from src.db.models import ReviewRuleJob
    from src.db.session import async_session

    stmt = select(ReviewRuleJob).where(ReviewRuleJob.workspace_id == ws)
    if repo_slug:
        stmt = stmt.where(ReviewRuleJob.repo_slug == repo_slug)
    stmt = stmt.order_by(ReviewRuleJob.created_at.desc()).limit(max(1, min(50, limit)))
    async with async_session() as s:
        return [job_to_dict(r) for r in (await s.scalars(stmt)).all()]


__all__ = [
    "DEFAULT_COUNT", "JOB_KINDS", "MAX_COUNT", "RULES_GENERATE_OPERATION",
    "RulesJobError", "build_repo_digest", "generate_rules", "get_job",
    "import_rules", "job_to_dict", "list_jobs", "markdown_sections",
    "parse_rules_reply", "run_job", "scan_convention_files", "start_job",
]
