"""Every generated document says what produced it.

A vault note is handed to a new developer, shown to an auditor, and committed
to a repository. It outlives the subscription that produced it — which is the
best thing about it, and also means it outlives every other place the answer to
"where did this come from" could have been kept.

Three reasons, each sufficient on its own:

  It is a compliance artefact. The CRA asks for technical documentation beside
  the inventory, and a document that cannot name its own revision is weaker
  evidence than one that can — the same argument that puts sha256 sums in the
  evidence pack.

  Documentation is where a model is freest to invent. A reader who knows a
  document came from one prompt with no lookups should weigh it differently
  from one written after twelve queries against the index. `research_calls` is
  what makes that difference visible rather than a matter of trust.

  Two documents in one vault will eventually disagree, and the answer is
  usually that they were generated months apart, from different commits, by
  different models. Without this it is unanswerable.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from src.vault.provenance import GENERATOR, as_footer, build

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"


# ─── the block ───────────────────────────────────────────────────────


def test_the_mark_is_always_present():
    block = build()
    assert block["generated_by"] == GENERATOR
    assert block["generated_at"]


def test_it_records_the_model_and_not_only_the_engine():
    """"api" covers gemini-3-pro and gpt-4o alike. Two documents a month apart
    under the same engine can differ entirely because of this."""
    block = build(engine="api", model="gemini-3-pro")
    assert block["engine"] == "api"
    assert block["model"] == "gemini-3-pro"


def test_absent_fields_are_omitted_rather_than_written_empty():
    """A key with no value reads as "we checked and there is none", which is a
    different claim from "this note predates the field"."""
    block = build()
    for key in ("engine", "model", "language", "commit", "tools_used"):
        assert key not in block


def test_research_calls_records_whether_it_looked_anything_up():
    """Zero on the agent engine means it answered from the prompt alone — the
    one thing that engine exists to prevent, now stated on the document."""
    assert build(tools_used=[])["research_calls"] == 0
    block = build(tools_used=["a", "a", "b"])
    assert block["research_calls"] == 3
    # The list is deduplicated for the reader; the count is not.
    assert block["tools_used"] == ["a", "b"]


def test_the_api_engine_claims_no_lookups_at_all():
    """It passes None, not an empty list: it does not do lookups by design, and
    "0 lookups" on a document that never could have made any is noise."""
    assert "research_calls" not in build(engine="api", model="m")


def test_a_missing_version_does_not_cost_somebody_their_documentation():
    """This runs inside a long background build."""
    assert build()["version"]


# ─── the footer ──────────────────────────────────────────────────────


def test_the_footer_survives_a_reader_who_never_opens_frontmatter():
    footer = as_footer(build(engine="claude_code", model="claude-opus-5",
                             commit="a1b2c3d4e5f6", tools_used=["x"] * 4))
    assert "celmis" in footer
    assert "claude_code" in footer
    assert "claude-opus-5" in footer
    assert "a1b2c3d4" in footer, "the commit is abbreviated, not dropped"
    assert "4 index lookups" in footer


def test_the_footer_degrades_instead_of_printing_holes():
    """A note written before this existed has an incomplete block, and a
    footer reading "engine: None" is worse than a short one."""
    footer = as_footer({"generated_by": "celmis"})
    assert footer == "Generated by celmis"
    assert "None" not in footer


# ─── it reaches the document, and the export ─────────────────────────


@pytest.mark.parametrize("module", [
    "module_prd.py", "feature_doc.py", "integration_doc.py",
])
def test_every_generator_stamps_what_it_wrote(module):
    text = (SRC / "generation" / module).read_text(encoding="utf-8")
    assert "provenance=_provenance(" in text, f"{module} writes an unmarked note"
    assert "tools_used=getattr(result" in text, (
        f"{module} drops the research evidence"
    )


def test_the_note_metadata_carries_it():
    writer = (SRC / "vault" / "writer.py").read_text(encoding="utf-8")
    assert "provenance: dict[str, Any] | None" in writer
    assert 'd["provenance"]' in writer, "it is never written to the frontmatter"


def test_the_export_carries_it_too():
    """A Word file attached to an email or a PDF in a filing is exactly the
    copy somebody hands over, and nobody opens the frontmatter of those. A mark
    that lives only in the .md marks the copies that never leave."""
    docs = (SRC / "api" / "routers" / "docs.py").read_text(encoding="utf-8")
    assert "as_footer" in docs
    assert 'post.metadata.get("provenance")' in docs


def test_the_engine_reports_the_model_it_used():
    engines = (SRC / "generation" / "engines.py").read_text(encoding="utf-8")
    assert re.search(r"model:\s*str \| None", engines), (
        "DocResult no longer carries the model, so the mark cannot name it"
    )


def test_the_version_is_a_real_version():
    """It looked up "celmis" — the product name — while pyproject calls the
    distribution "code-analysis-system", so every document carried
    version: unknown. A field that is always the same string is worse than no
    field: it looks like an answer.

    `!= "unknown"` was too narrow to notice the same failure return in a new
    costume. `src/__init__.py` later became a metadata lookup of its own,
    which setuptools evaluated BEFORE the install existed — so the build baked
    "0.0.0+unknown" into the distribution and every read handed it straight
    back. Production's `/api/capabilities` answered

        "api_version": "0.0.0+unknown"

    and this test was green throughout, because "0.0.0+unknown" is not
    "unknown".

    So: the assertion is on what a version has to BE, not on the placeholders
    seen so far. It must parse, and it must not be the all-zero release that
    every "I don't know" in this codebase has reached for.
    """
    value = build()["version"]
    assert value and value != "unknown", (
        "the distribution name in provenance.py does not match pyproject.toml"
    )
    numbers = value.split("+", 1)[0]
    parts = numbers.split(".")
    assert len(parts) >= 2 and all(p.isdigit() for p in parts[:2]), (
        f"{value!r} is not a version number"
    )
    assert any(int(p) for p in parts if p.isdigit()), (
        f"{value!r} is 0.0.0 — the string this codebase reaches for when it "
        f"does not know, dressed as a release"
    )
