"""VaultWriter — writes MD files into the vault + upserts into Qdrant.

Before being written, snippets go through the redactor. The frontmatter is
structured for filtering in Qdrant.
"""

from __future__ import annotations

import hashlib
import logging
from contextlib import contextmanager
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import frontmatter

from src.config import Settings, get_settings
from src.retrieval.tier1_vault import VaultRetriever
from src.security.redactor import redact

logger = logging.getLogger(__name__)


#: Frontmatter keys NoteMetadata models explicitly. Anything else in a note's
#: frontmatter is a per-type extra — an integration's `service`, a feature's
#: owner — and belongs in `extra` rather than being silently discarded.
_KNOWN_FRONTMATTER_KEYS = frozenset({
    "type", "repo", "analyzed_at", "commit", "module", "feature", "path",
    "symbols", "entry_points", "keywords", "external_deps", "used_by",
    "cross_refs", "security_findings", "provenance", "computed",
})


@dataclass
class NoteMetadata:
    """Frontmatter block of a vault note.

    The frontmatter is split into TWO blocks:
      * STATIC — generated by the LLM, governed by the resume hash (`commit`).
      * COMPUTED — computed from the graph without an LLM, always refreshed on
        the next `enrich`/`generate`. Incrementality is not broken, because
        there is no LLM cost for computed.

    Computed fields are passed via the `computed` dict (from
    CrossRefsComputer.as_dict()). The split kept here is purely logical — in
    the YAML they live in one and the same frontmatter; the reader does not
    tell them apart.
    """

    type: str  # module | feature | integration | overview | security
    repo: str
    analyzed_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    commit: str | None = None
    module: str | None = None
    feature: str | None = None
    path: str | None = None  # path relative to the repo (for the module type)
    symbols: list[str] = field(default_factory=list)
    entry_points: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)
    external_deps: list[str] = field(default_factory=list)
    used_by: list[str] = field(default_factory=list)
    # cross_refs — used to be static, now it migrates into the computed block.
    # The field is kept for backward-compat on `write` without computed; new
    # generations pass it via `computed["cross_refs"]`.
    cross_refs: list[str] = field(default_factory=list)
    security_findings: int = 0
    #: What produced this document — see src/vault/provenance.py. A note is
    #: handed to a new developer, shown to an auditor and committed to a
    #: repository; it outlives every other place this answer could be kept.
    provenance: dict[str, Any] | None = None
    extra: dict[str, Any] = field(default_factory=dict)
    # COMPUTED — graph-derived dict (cross_refs, callers_modules, counts, schema_version).
    # Passed from CrossRefsComputer.as_dict(). None means "computed has not
    # been computed yet".
    computed: dict[str, Any] | None = None

    def as_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "type": self.type,
            "repo": self.repo,
            "analyzed_at": self.analyzed_at,
        }
        for key in (
            "commit",
            "module",
            "feature",
            "path",
            "symbols",
            "entry_points",
            "keywords",
            "external_deps",
            "used_by",
        ):
            val = getattr(self, key)
            if val not in (None, [], ""):
                d[key] = val
        # cross_refs: computed["cross_refs"] takes priority over the static
        # self.cross_refs (during the migration to computed fields the static
        # one stays for backward-compat).
        if self.computed and self.computed.get("cross_refs"):
            d["cross_refs"] = list(self.computed["cross_refs"])
        elif self.cross_refs:
            d["cross_refs"] = list(self.cross_refs)
        if self.security_findings:
            d["security_findings"] = self.security_findings
        if self.provenance:
            d["provenance"] = dict(self.provenance)
        if self.extra:
            d.update(self.extra)
        # COMPUTED block (except cross_refs, which was already added above)
        if self.computed:
            for k in (
                "callers_modules",
                "outgoing_call_count",
                "incoming_call_count",
                "graph_centrality",
                "computed_at",
                "computed_schema_version",
            ):
                if k in self.computed and self.computed[k] not in (None, [], ""):
                    d[k] = self.computed[k]
        return d


class VaultWriter:
    """Writes into the vault and (optionally) syncs Qdrant."""

    def __init__(
        self,
        settings: Settings | None = None,
        vault_retriever: VaultRetriever | None = None,
        *,
        workspace_id: str | None,
    ) -> None:
        """`workspace_id` is required — keyword, no default.

        It used to default to "default", which normalises to None, so a
        writer built without one wrote Qdrant points with no tenant. Those
        are invisible to every workspace afterwards. Not a hole — the
        fail-closed direction — but a silent LOSS: the documentation is
        generated, stored, billed, and never found again.

        None is still accepted, and means something different from omitting
        it: the caller ASKED whose repository this is and got no answer. It
        is logged when it happens; forgetting to ask no longer compiles.
        """
        self.settings = settings or get_settings()
        self.workspace_id = workspace_id
        if not workspace_id or workspace_id == "default":
            logger.warning(
                "vault_write_unattributed — notes written by this writer will "
                "be invisible to every workspace; resolve the repository's "
                "workspace before writing",
            )
        self.vault_retriever = vault_retriever  # lazy — if a Qdrant upsert is needed
        # Stage 18 — batching V1. None = pass-through (send per-note).
        # list = buffer active (in `batched_qdrant()` context).
        self._qdrant_queue: list[tuple[str, str, dict]] | None = None
        self._qdrant_depth: int = 0
        #: Notes successfully written into the vector store, and the reasons
        #: any batch failed. Read by the job handler, which used to have no
        #: way to know: the flush below swallowed every exception, so a run
        #: that produced documents and ZERO vectors reported `completed`,
        #: `attempts: 1`, `last_error: null`. On production that left three
        #: repositories with markdown notes, an empty Qdrant, and a chat
        #: banner telling the user to generate the vault they had just
        #: generated — a loop with no exit.
        self.qdrant_upserted: int = 0
        self.qdrant_failures: list[str] = []

    def write(
        self,
        *,
        repo: str,
        relative_path: str,  # inside projects/{repo}/, e.g. "modules/auth.md"
        content: str,
        metadata: NoteMetadata,
        redact_content: bool = True,
        index_in_qdrant: bool = True,
    ) -> Path:
        """Writes the note. Returns the absolute path."""
        if redact_content:
            # Gemini output is markdown, we use the mode without detect-secrets
            # (it produces false positives on ordinary words such as
            # 'Architecture')
            content, stats = redact(content, source_hint=relative_path, mode="markdown")
            if stats.secrets_found > 0:
                logger.warning(
                    "vault_redaction_applied path=%s secrets=%d patterns=%s",
                    relative_path,
                    stats.secrets_found,
                    stats.patterns_matched,
                )

        full_path = self.settings.repo_vault_path(repo) / relative_path
        full_path.parent.mkdir(parents=True, exist_ok=True)

        post = frontmatter.Post(content, **metadata.as_dict())
        full_path.write_text(frontmatter.dumps(post), encoding="utf-8")
        logger.info("vault_write path=%s bytes=%d", relative_path, full_path.stat().st_size)

        # Stage 20 — reverse-index cache is stale as soon as any MD is
        # written (new source_files/symbols may appear). Drop the cache
        # so the next incremental sync rebuilds from disk.
        try:
            from src.vault.reverse_index import invalidate_cache
            invalidate_cache(repo)
        except Exception as exc:  # noqa: BLE001
            logger.debug("reverse_index_invalidate_failed repo=%s err=%s", repo, exc)

        if index_in_qdrant:
            # Qdrant upsert — NOT fatal. If the embed fails (429, network), the
            # vault file stays. Later on `analyzer reindex-qdrant` re-pushes
            # everything from disk.
            try:
                self._upsert_qdrant(relative_path, content, metadata)
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "qdrant_upsert_failed path=%s err=%s — vault saved, skip embedding",
                    relative_path,
                    type(exc).__name__,
                )
        return full_path

    def _upsert_qdrant(
        self,
        relative_path: str,
        content: str,
        metadata: NoteMetadata,
    ) -> None:
        if self.vault_retriever is None:
            self.vault_retriever = VaultRetriever(settings=self.settings, workspace_id=self.workspace_id)

        note_id = self._note_id(metadata.repo, relative_path)
        embed_text = self._make_embed_text(relative_path, content, metadata)
        payload = {
            **metadata.as_dict(),
            "note_path": relative_path,
        }

        # Stage 18 (batching V1): if a `batched_qdrant()` context is
        # active on this writer, buffer instead of firing one HTTP call
        # per note. The orchestrator wraps each generation loop in
        # `with writer.batched_qdrant():` — buffer drains on exit.
        if getattr(self, "_qdrant_queue", None) is not None:
            self._qdrant_queue.append((note_id, embed_text, payload))
            return

        self.vault_retriever.upsert_note(
            note_id=note_id,
            content=embed_text,
            payload=payload,
        )

    # ─── Batching V1 (Stage 18) ─────────────────────────────────────

    @contextmanager
    def batched_qdrant(self):
        """Buffer per-note Qdrant upserts and flush on exit.

        Use around generator loops:
            with writer.batched_qdrant():
                for feature in features:
                    writer.write(...)      # embeds NOT sent yet
            # single batched embed HTTP call fires here

        Nested `with` blocks share the outer buffer — the innermost
        exit is a no-op, outermost flushes. Simple counter-based.
        """
        if self._qdrant_queue is None:
            self._qdrant_queue = []
            self._qdrant_depth = 1
        else:
            self._qdrant_depth += 1
        try:
            yield
        finally:
            self._qdrant_depth -= 1
            if self._qdrant_depth == 0:
                queue = self._qdrant_queue or []
                self._qdrant_queue = None
                if queue:
                    if self.vault_retriever is None:
                        self.vault_retriever = VaultRetriever(settings=self.settings, workspace_id=self.workspace_id)
                    try:
                        self.vault_retriever.upsert_notes_batch(queue)
                        self.qdrant_upserted += len(queue)
                        logger.info(
                            "qdrant_batch_flushed count=%d", len(queue),
                        )
                    except Exception as exc:  # noqa: BLE001
                        # Still not raised here — the vault files exist on disk
                        # and losing them to an exception would be worse. But
                        # it is no longer INVISIBLE: the failure is recorded so
                        # the caller can decide, and the job handler now does.
                        self.qdrant_failures.append(
                            f"{type(exc).__name__}: {str(exc)[:160]}"
                        )
                        logger.warning(
                            "qdrant_batch_upsert_failed count=%d err=%s — "
                            "vault MDs still on disk, run `analyzer "
                            "reindex-qdrant` to recover",
                            len(queue), type(exc).__name__,
                        )

    # ─── computed-fields update (shallow, no LLM) ───────────────────────
    # Used for cascading invalidation: when the graph has changed, we recompute
    # only the computed block and do not touch the body of the note.
    # If the computed block did not actually change — skip the re-embed (this
    # saves Gemini quota).
    COMPUTED_FIELDS_KEYS = (
        "cross_refs",
        "callers_modules",
        "outgoing_call_count",
        "incoming_call_count",
        "graph_centrality",
        "computed_at",
        "computed_schema_version",
    )

    def update_computed_fields(
        self,
        *,
        repo: str,
        relative_path: str,
        computed: dict[str, Any],
        index_in_qdrant: bool = True,
    ) -> bool:
        """Rewrites the computed block in the frontmatter of an existing note.

        The body of the note and the static frontmatter do not change. If the
        new computed is identical to the existing one — no-op (returns False,
        without a disk write and without a re-embed).

        Returns: True if something was actually written (computed changed),
        False if it was a no-op.
        """
        full_path = self.settings.repo_vault_path(repo) / relative_path
        if not full_path.exists():
            logger.debug("update_computed_skip_missing path=%s", relative_path)
            return False

        post = frontmatter.load(full_path)
        existing_relevant = {
            k: post.metadata.get(k)
            for k in self.COMPUTED_FIELDS_KEYS
            if k in post.metadata
        }
        new_relevant = {
            k: computed.get(k) for k in self.COMPUTED_FIELDS_KEYS if k in computed
        }
        # Skip computed_at in the diff — it is always different (timestamp).
        # We look at the semantics.
        existing_relevant.pop("computed_at", None)
        new_relevant.pop("computed_at", None)
        if existing_relevant == new_relevant:
            logger.debug("update_computed_noop path=%s", relative_path)
            return False

        # Replace computed keys (delete the old ones, set the new ones)
        for k in self.COMPUTED_FIELDS_KEYS:
            post.metadata.pop(k, None)
        for k, v in computed.items():
            if k in self.COMPUTED_FIELDS_KEYS and v not in (None, [], ""):
                post.metadata[k] = v

        full_path.write_text(frontmatter.dumps(post), encoding="utf-8")
        logger.info(
            "computed_updated path=%s cross_refs=%d callers=%d",
            relative_path,
            len(computed.get("cross_refs", [])),
            len(computed.get("callers_modules", [])),
        )

        if index_in_qdrant:
            try:
                # Re-embed: the frontmatter is updated → embed_text includes
                # cross_refs. We take into account that the content stayed the
                # same — only the metadata was updated. We assemble NoteMetadata
                # from the post.metadata that was read + the applied computed.
                meta = self._metadata_from_dict(post.metadata, repo)
                self._upsert_qdrant(relative_path, post.content, meta)
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "qdrant_re_embed_failed path=%s err=%s",
                    relative_path,
                    type(exc).__name__,
                )
        return True

    @staticmethod
    def _metadata_from_dict(d: dict[str, Any], repo: str) -> NoteMetadata:
        """Reconstruct NoteMetadata from a frontmatter dict (for the re-embed
        flow)."""
        return NoteMetadata(
            type=str(d.get("type", "module")),
            repo=repo,
            analyzed_at=str(d.get("analyzed_at", datetime.now(UTC).isoformat())),
            commit=d.get("commit"),
            module=d.get("module"),
            feature=d.get("feature"),
            path=d.get("path"),
            symbols=list(d.get("symbols", []) or []),
            entry_points=list(d.get("entry_points", []) or []),
            keywords=list(d.get("keywords", []) or []),
            external_deps=list(d.get("external_deps", []) or []),
            used_by=list(d.get("used_by", []) or []),
            cross_refs=list(d.get("cross_refs", []) or []),
            security_findings=int(d.get("security_findings", 0) or 0),
            # The .md on disk keeps these; the re-embed rebuilt the metadata
            # from scratch and dropped them, so the SEARCH payload lost the
            # provenance block, note-specific extras such as an integration's
            # `service`, and every computed field except cross_refs — which are
            # the fields this call exists to publish.
            provenance=d.get("provenance") or None,
            computed=d.get("computed") or None,
            extra={
                k: v for k, v in d.items()
                if k not in _KNOWN_FRONTMATTER_KEYS
            },
        )

    @staticmethod
    def note_id(repo: str, relative_path: str) -> str:
        """Deterministic UUID-5-style id based on (repo, path)."""
        raw = f"{repo}:{relative_path}".encode()
        return hashlib.sha1(raw).hexdigest()[:32]

    _note_id = note_id  # backward-compat alias

    @staticmethod
    def _make_embed_text(path: str, content: str, metadata: NoteMetadata) -> str:
        """Text for the embedding — the key metadata + the first chunk of the
        content."""
        parts = [
            f"Path: {path}",
            f"Type: {metadata.type}",
        ]
        if metadata.module:
            parts.append(f"Module: {metadata.module}")
        if metadata.feature:
            parts.append(f"Feature: {metadata.feature}")
        if metadata.keywords:
            parts.append(f"Keywords: {', '.join(metadata.keywords)}")
        if metadata.symbols:
            parts.append(f"Symbols: {', '.join(metadata.symbols[:20])}")
        parts.append("")
        # Max ~6000 chars from the content → roughly 1500-2000 tokens
        parts.append(content[:6000])
        return "\n".join(parts)
