"""Three places where somebody else's words reached a user unedited.

Each is the same shape as the review path's `local_timeout`, one layer out: a
message written for an operator — or for nobody at all — rendered verbatim
where a person reads it.

  * A duplicate project name answered with the asyncpg exception class, the
    constraint name, the column names and the OWNER'S INTERNAL ID.
  * A generated document's provenance footer carried the workspace UUID inside
    the model name, in a Word file people download and forward.
  * Sixteen locales told users their conversations came "from the legacy
    Streamlit" — a surface removed before this version shipped.
"""

from __future__ import annotations

import json
import pathlib

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[2]


# ─── the 409 a browser renders ───────────────────────────────────────


def test_a_duplicate_project_name_says_what_to_do():
    """What the caller gets is one sentence naming the conflict and the fix."""
    import inspect

    from src.api.repositories import create_project

    src = inspect.getsource(create_project)
    assert "already exists. Pick another name." in src


def test_the_driver_s_own_message_does_not_travel():
    """`{e.orig}` is the asyncpg exception. It went out in the response body:
    class name, constraint, columns, and the owner's uuid."""
    import inspect

    from src.api.repositories import create_project

    src = inspect.getsource(create_project)
    raise_line = [ln for ln in src.splitlines() if "raise ValueError" in ln]
    assert raise_line, "the conflict no longer raises"
    assert not any("e.orig" in ln for ln in raise_line), (
        "the database's message is back in the user's error"
    )


def test_the_operator_can_still_read_the_original():
    """`from e` keeps the real cause on the exception chain, and a log line
    names the conflict. Hiding it from the USER is not hiding it."""
    import inspect

    from src.api.repositories import create_project

    src = inspect.getsource(create_project)
    assert "from e" in src
    assert "project_name_conflict" in src


# ─── the mark on a document that leaves the building ─────────────────


@pytest.mark.parametrize(
    ("stored", "expected"),
    [
        # The gateway names a deployment after the workspace it belongs to.
        ("litellm_proxy/celmis-2f4c96aa-9454-49b7-9fa7-9975f5df5c56-chat",
         "litellm_proxy/celmis-chat"),
        ("litellm_proxy/celmis-abc-review", "litellm_proxy/celmis-review"),
        # Anything without an installation id is nobody's business but its own.
        ("gemini/gemini-3.1-pro-preview", "gemini/gemini-3.1-pro-preview"),
        ("claude-sonnet-4-6", "claude-sonnet-4-6"),
    ],
)
def test_the_footer_keeps_the_model_and_drops_the_workspace(stored, expected):
    from src.vault.provenance import _public_model

    assert _public_model(stored) == expected


def test_the_footer_still_says_who_wrote_the_document():
    """The mark is not being weakened — a reader must still learn the product,
    the version, the engine and the commit."""
    from src.vault.provenance import as_footer

    line = as_footer({
        "generated_by": "celmis", "version": "0.1.0", "engine": "api",
        "model": "litellm_proxy/celmis-2f4c96aa-9454-49b7-9fa7-9975f5df5c56-chat",
        "commit": "575b3a2ad0", "generated_at": "2026-08-25T10:31:34+00:00",
    })
    assert "Generated by celmis 0.1.0" in line
    assert "engine: api" in line and "commit: 575b3a2a" in line
    assert "2f4c96aa" not in line, "the workspace id is on the document"


# ─── a surface that no longer exists ─────────────────────────────────


def test_no_locale_mentions_a_removed_surface():
    """Streamlit was the pre-Next.js UI. A string that describes a product the
    user cannot have is worse than a missing one: it is the product being
    wrong about itself, in sixteen languages."""
    offenders = []
    for f in sorted((ROOT / "web/lib/i18n/messages").glob("*.json")):
        blob = json.dumps(json.loads(f.read_text(encoding="utf-8")),
                          ensure_ascii=False).lower()
        if "streamlit" in blob:
            offenders.append(f.name)
    assert not offenders, f"still naming Streamlit at the user: {offenders}"


def test_every_locale_still_describes_the_chats_page():
    """Deleting the sentence would have been the other way to pass."""
    for f in sorted((ROOT / "web/lib/i18n/messages").glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        assert d.get("chats.description", "").strip(), f.name
