"use client";

/**
 * /admin/review-rules — the review rules library of the workspace.
 *
 * A rule is something every reviewer agent is told to enforce: workspace-wide,
 * or for one repository (where a rule with the same title replaces the
 * workspace one). Rules arrive from four places — written here, copied from
 * the built-in library, generated by the review model from the repository,
 * or imported from the repository's own convention files — and everything a
 * machine wrote arrives PENDING: nothing reaches a review until somebody
 * approves it here.
 *
 * `?repo=<slug>` opens a repository's rules directly (the repo policy page
 * links here from its "Rules" tab).
 */

import Link from "next/link";
import { useMemo, useState, useSyncExternalStore } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  BookOpenIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  FileDownIcon,
  ListChecksIcon,
  Loader2Icon,
  PlusIcon,
  SaveIcon,
  SparklesIcon,
  Trash2Icon,
  XIcon,
} from "lucide-react";

import {
  api,
  reviewRulesApi,
  type LibraryRule,
  type RepoOut,
  type ReviewRule,
  type ReviewRuleIn,
  type ReviewRuleJob,
  type ReviewRuleSeverity,
  type ReviewRuleStatus,
} from "@/lib/api";
import { useToken } from "@/lib/use-token";
import { useT } from "@/lib/i18n";
import { PageHeader, PageShell } from "@/components/page-shell";
import { SectionTabs } from "@/components/section-tabs";
import {
  Card, CardContent, CardDescription, CardHeader, CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Callout } from "@/components/ui/callout";
import { useConfirm } from "@/components/ui/confirm-dialog";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type Filter = "all" | ReviewRuleStatus;
const FILTERS: Filter[] = ["all", "active", "pending", "rejected"];
const SEVERITIES: ReviewRuleSeverity[] = ["info", "warning", "error", "critical"];
/** Server limits (src/review/rules_store.py), repeated so a value is refused
 *  at the keyboard rather than by a 422. */
const MAX_TITLE = 200;
const MAX_INSTRUCTIONS = 2000;
const MAX_EXAMPLE = 2000;

const SEVERITY_VARIANT: Record<ReviewRuleSeverity, "destructive" | "warning" | "outline" | "default"> = {
  critical: "destructive",
  error: "destructive",
  warning: "warning",
  info: "outline",
};

/** `?repo=` — the repository whose rules to open, or null. */
function repoFromUrl(): string | null {
  return new URLSearchParams(window.location.search).get("repo") || null;
}
const noSubscribe = () => () => {};

function SeverityBadge({ severity }: { severity: ReviewRuleSeverity }) {
  const t = useT();
  return (
    <Badge variant={SEVERITY_VARIANT[severity] ?? "outline"} className="text-[10px] uppercase">
      {t(`admin.reviewRules.severity.${severity}`)}
    </Badge>
  );
}

function OriginTag({ origin }: { origin: ReviewRule["origin"] }) {
  const t = useT();
  if (origin === "manual") return null;
  return (
    <Badge variant="brand" className="text-[10px]">
      {t(`admin.reviewRules.origin.${origin}`)}
    </Badge>
  );
}

export default function ReviewRulesPage() {
  const t = useT();
  const token = useToken();
  const qc = useQueryClient();
  const { confirm, dialog } = useConfirm();

  const urlRepo = useSyncExternalStore(noSubscribe, repoFromUrl, () => null);
  // undefined = follow the URL; null = the workspace scope; a slug = that repo.
  const [chosenRepo, setChosenRepo] = useState<string | null | undefined>(undefined);
  const repo = chosenRepo === undefined ? urlRepo : chosenRepo;
  const [repoQuery, setRepoQuery] = useState("");
  const [filter, setFilter] = useState<Filter>("all");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [expanded, setExpanded] = useState<number | null>(null);
  const [creating, setCreating] = useState(false);
  const [libraryOpen, setLibraryOpen] = useState(false);
  const [job, setJob] = useState<ReviewRuleJob | null>(null);

  const chooseRepo = (slug: string | null) => {
    setChosenRepo(slug);
    setSelected(new Set());
    setExpanded(null);
    const url = new URL(window.location.href);
    if (slug) url.searchParams.set("repo", slug);
    else url.searchParams.delete("repo");
    window.history.replaceState(window.history.state, "", url.toString());
  };

  const repos = useQuery({
    queryKey: ["repos"],
    queryFn: () => api<RepoOut[]>("/api/repos", { token }),
    enabled: !!token,
  });
  const repoSlugs = useMemo(
    () => (repos.data ?? []).map((r) => r.slug).sort((a, b) => a.localeCompare(b)),
    [repos.data],
  );

  const list = useQuery({
    queryKey: ["review-rules", repo ?? "", filter],
    queryFn: () => reviewRulesApi.list(token!, {
      scope: repo ? "repo" : "workspace",
      repo,
      status: filter === "all" ? null : filter,
    }),
    enabled: !!token,
  });
  const canEdit = !!list.data?.can_edit;

  const visible = useMemo(() => {
    const needle = search.trim().toLowerCase();
    const rows = list.data?.rules ?? [];
    if (!needle) return rows;
    return rows.filter((r) =>
      `${r.title} ${r.instructions} ${r.path_glob}`.toLowerCase().includes(needle));
  }, [list.data, search]);

  const refresh = () => {
    qc.invalidateQueries({ queryKey: ["review-rules"] });
    qc.invalidateQueries({ queryKey: ["review-rules-library"] });
  };

  // ── the background job (generate / import) and its progress. Polled from
  // the handler that started it rather than from an effect: when it ends,
  // the list is reloaded and switched to "Pending", where proposals land.
  const pollJob = async (first: ReviewRuleJob) => {
    let current = first;
    setJob(current);
    while (current.status === "queued" || current.status === "running") {
      await new Promise((resolve) => setTimeout(resolve, 1500));
      try {
        current = await reviewRulesApi.job(token!, current.id);
      } catch {
        continue;
      }
      setJob(current);
    }
    if (current.status === "completed") {
      setFilter("pending");
      setSelected(new Set());
      refresh();
    }
  };

  const startJob = useMutation({
    mutationFn: (kind: "generate" | "import") => kind === "generate"
      ? reviewRulesApi.generate(token!, repo!)
      : reviewRulesApi.importFromRepo(token!, repo!),
    onSuccess: (j) => { void pollJob(j); },
    onError: (e) => toast.error(t("admin.reviewRules.jobFailed", { message: (e as Error).message })),
  });

  const bulk = useMutation({
    mutationFn: async (action: "active" | "rejected" | "delete") => {
      const ids = Array.from(selected);
      if (action === "delete") return reviewRulesApi.bulkDelete(token!, ids);
      return reviewRulesApi.bulkStatus(token!, ids, action);
    },
    onSuccess: (_r, action) => {
      setSelected(new Set());
      refresh();
      toast.success(t(`admin.reviewRules.bulkDone.${action}`));
    },
    onError: (e) => toast.error(t("admin.reviewRules.saveFailed", { message: (e as Error).message })),
  });

  const removeSelected = async () => {
    const ok = await confirm({
      title: t("admin.reviewRules.confirmDelete", { count: selected.size }),
      confirmLabel: t("common.delete"),
      danger: true,
    });
    if (ok) bulk.mutate("delete");
  };

  const toggle = (id: number) => setSelected((prev) => {
    const next = new Set(prev);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    return next;
  });
  const allSelected = visible.length > 0 && visible.every((r) => selected.has(r.id));
  const toggleAll = () => setSelected(allSelected ? new Set() : new Set(visible.map((r) => r.id)));

  const counts = list.data?.counts;
  const running = job?.status === "queued" || job?.status === "running";

  return (
    <PageShell width="wide">
      <PageHeader
        icon={<ListChecksIcon className="h-6 w-6" />}
        title={t("admin.reviewRules.title")}
        description={t("admin.reviewRules.description")}
        tabs={<SectionTabs set="review" />}
      />

      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base">{t("admin.reviewRules.scopeTitle")}</CardTitle>
          <CardDescription>{t("admin.reviewRules.scopeDesc")}</CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-3 sm:flex-row sm:items-end">
          <div className="sm:w-56">
            <Label htmlFor="rr-scope">{t("admin.reviewRules.scopeLabel")}</Label>
            <Select
              id="rr-scope"
              className="w-full"
              value={repo ? "repo" : "workspace"}
              onChange={(v) => {
                if (v === "workspace") chooseRepo(null);
                else if (repoSlugs.length) chooseRepo(repo ?? repoSlugs[0]);
              }}
              options={[
                { value: "workspace", label: t("admin.reviewRules.scopeWorkspace") },
                { value: "repo", label: t("admin.reviewRules.scopeRepo"),
                  disabled: repoSlugs.length === 0 },
              ]}
            />
          </div>
          {repo && (
            <div className="flex-1">
              <Label htmlFor="rr-repo">{t("admin.reviewRules.repoLabel")}</Label>
              <Input
                id="rr-repo"
                list="rr-repos"
                value={repoQuery || repo}
                placeholder={t("admin.reviewRules.repoSearch")}
                onChange={(e) => {
                  setRepoQuery(e.target.value);
                  if (repoSlugs.includes(e.target.value)) {
                    chooseRepo(e.target.value);
                    setRepoQuery("");
                  }
                }}
              />
              <datalist id="rr-repos">
                {repoSlugs.map((s) => <option key={s} value={s} />)}
              </datalist>
            </div>
          )}
        </CardContent>
      </Card>

      {repo && list.data && list.data.workspace_active_count > 0 && (
        <Callout tone="info">
          {t("admin.reviewRules.workspaceAlsoApplies", {
            count: list.data.workspace_active_count,
          })}
        </Callout>
      )}

      {canEdit && (
        <div className="flex flex-wrap gap-2">
          <Button onClick={() => { setCreating(true); setExpanded(null); }} disabled={creating}>
            <PlusIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.addRule")}
          </Button>
          <Button variant="outline" onClick={() => setLibraryOpen(true)}>
            <BookOpenIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.addFromLibrary")}
          </Button>
          <Button
            variant="outline"
            onClick={() => startJob.mutate("generate")}
            disabled={!repo || running || startJob.isPending}
            title={repo ? undefined : t("admin.reviewRules.needsRepo")}
          >
            <SparklesIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.generate")}
          </Button>
          <Button
            variant="outline"
            onClick={() => startJob.mutate("import")}
            disabled={!repo || running || startJob.isPending}
            title={repo ? undefined : t("admin.reviewRules.needsRepo")}
          >
            <FileDownIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.import")}
          </Button>
          {!repo && (
            <p className="w-full text-xs text-[var(--color-muted-foreground)]">
              {t("admin.reviewRules.needsRepo")}
            </p>
          )}
        </div>
      )}

      {job && <JobBanner job={job} onClose={() => setJob(null)} />}

      {creating && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">{t("admin.reviewRules.newRule")}</CardTitle>
            <CardDescription>
              {repo
                ? t("admin.reviewRules.newRuleRepo", { repo })
                : t("admin.reviewRules.newRuleWorkspace")}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <RuleEditor
              agents={list.data?.target_agents ?? []}
              onCancel={() => setCreating(false)}
              onSave={async (payload) => {
                await reviewRulesApi.create(token!, { ...payload, repo_slug: repo, status: "active" });
                setCreating(false);
                refresh();
                toast.success(t("admin.reviewRules.created"));
              }}
            />
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader className="pb-3">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-wrap gap-1" role="tablist">
              {FILTERS.map((f) => (
                <Button
                  key={f}
                  size="sm"
                  role="tab"
                  aria-selected={filter === f}
                  variant={filter === f ? "secondary" : "ghost"}
                  onClick={() => { setFilter(f); setSelected(new Set()); }}
                >
                  {t(`admin.reviewRules.filter.${f}`)}
                  {counts && (f === "pending" || f === "all") && (
                    <span className="ml-1 text-[var(--color-muted-foreground)]">
                      ({counts[f]})
                    </span>
                  )}
                </Button>
              ))}
            </div>
            <Input
              className="sm:w-64"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder={t("admin.reviewRules.searchPlaceholder")}
            />
          </div>
        </CardHeader>
        <CardContent className="space-y-2">
          {canEdit && selected.size > 0 && (
            <div className="flex flex-wrap items-center gap-2 rounded-md border border-[var(--color-border)] bg-[var(--color-muted)]/40 p-2 text-sm">
              <span className="mr-2">{t("admin.reviewRules.selected", { count: selected.size })}</span>
              <Button size="sm" onClick={() => bulk.mutate("active")} disabled={bulk.isPending}>
                <CheckIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.approve")}
              </Button>
              <Button size="sm" variant="outline" onClick={() => bulk.mutate("rejected")}
                      disabled={bulk.isPending}>
                <XIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.reject")}
              </Button>
              <Button size="sm" variant="ghost" onClick={removeSelected} disabled={bulk.isPending}>
                <Trash2Icon className="h-4 w-4 mr-1 text-red-600" /> {t("common.delete")}
              </Button>
            </div>
          )}

          {list.isLoading && (
            <p className="text-sm text-[var(--color-muted-foreground)]">{t("common.loading")}</p>
          )}
          {list.error && (
            <Callout tone="danger">{(list.error as Error).message}</Callout>
          )}
          {!list.isLoading && visible.length === 0 && (
            <EmptyState
              icon={ListChecksIcon}
              title={t("admin.reviewRules.emptyTitle")}
              description={t("admin.reviewRules.emptyDesc")}
            />
          )}

          {visible.length > 0 && canEdit && (
            <label className="flex items-center gap-2 px-1 text-xs text-[var(--color-muted-foreground)]">
              <input type="checkbox" checked={allSelected} onChange={toggleAll}
                     aria-label={t("admin.reviewRules.selectAll")} />
              {t("admin.reviewRules.selectAll")}
            </label>
          )}

          {visible.map((rule) => (
            <RuleRow
              key={rule.id}
              rule={rule}
              canEdit={canEdit}
              agents={list.data?.target_agents ?? []}
              checked={selected.has(rule.id)}
              onCheck={() => toggle(rule.id)}
              open={expanded === rule.id}
              onToggle={() => setExpanded(expanded === rule.id ? null : rule.id)}
              onChanged={refresh}
            />
          ))}
        </CardContent>
      </Card>

      {repo && (list.data?.legacy_folder_rules.length ?? 0) > 0 && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">{t("admin.reviewRules.legacyTitle")}</CardTitle>
            <CardDescription>
              {t("admin.reviewRules.legacyDesc")}{" "}
              <Link className="underline" href={`/admin/review-policies/${encodeURIComponent(repo)}?tab=rules`}>
                {t("admin.reviewRules.legacyLink")}
              </Link>
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {list.data!.legacy_folder_rules.map((fr, i) => (
              <div key={i} className="rounded-md border border-[var(--color-border)] p-2 text-sm">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-medium">{fr.title || fr.pattern}</span>
                  <Badge variant="outline" className="font-mono text-[10px]">{fr.pattern}</Badge>
                </div>
                <p className="mt-1 whitespace-pre-wrap text-[var(--color-muted-foreground)]">{fr.prompt}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      <LibraryDialog
        open={libraryOpen}
        onOpenChange={setLibraryOpen}
        repo={repo}
        onAdded={refresh}
      />
      {dialog}
    </PageShell>
  );
}


function JobBanner({ job, onClose }: { job: ReviewRuleJob; onClose: () => void }) {
  const t = useT();
  const kind = t(`admin.reviewRules.jobKind.${job.kind}`);
  if (job.status === "failed") {
    return (
      <Callout tone="danger">
        <div className="flex items-start justify-between gap-2">
          <span>{t("admin.reviewRules.jobFailed", { message: job.error || kind })}</span>
          <Button size="sm" variant="ghost" onClick={onClose} aria-label={t("common.cancel")}>
            <XIcon className="h-4 w-4" />
          </Button>
        </div>
      </Callout>
    );
  }
  if (job.status === "completed") {
    return (
      <Callout tone="success">
        <div className="flex items-start justify-between gap-2">
          <span>
            {t("admin.reviewRules.jobDone", {
              kind, count: job.result.created?.length ?? 0, skipped: job.result.skipped ?? 0,
            })}
          </span>
          <Button size="sm" variant="ghost" onClick={onClose} aria-label={t("common.cancel")}>
            <XIcon className="h-4 w-4" />
          </Button>
        </div>
      </Callout>
    );
  }
  return (
    <Callout tone="info">
      <span className="inline-flex items-center gap-2">
        <Loader2Icon className="h-4 w-4 animate-spin" />
        {t("admin.reviewRules.jobRunning", { kind, progress: job.progress || "…" })}
      </span>
    </Callout>
  );
}


function RuleRow({
  rule, canEdit, agents, checked, onCheck, open, onToggle, onChanged,
}: {
  rule: ReviewRule;
  canEdit: boolean;
  agents: string[];
  checked: boolean;
  onCheck: () => void;
  open: boolean;
  onToggle: () => void;
  onChanged: () => void;
}) {
  const t = useT();
  const token = useToken();
  const setStatus = useMutation({
    mutationFn: (status: ReviewRuleStatus) => reviewRulesApi.update(token!, rule.id, { status }),
    onSuccess: () => onChanged(),
    onError: (e) => toast.error(t("admin.reviewRules.saveFailed", { message: (e as Error).message })),
  });

  return (
    <div className="rounded-md border border-[var(--color-border)]">
      <div className="flex items-start gap-2 p-2">
        {canEdit && (
          <input type="checkbox" className="mt-1.5" checked={checked} onChange={onCheck}
                 aria-label={t("admin.reviewRules.selectRule", { title: rule.title })} />
        )}
        <button type="button" onClick={onToggle}
                className="flex min-w-0 flex-1 items-start gap-2 text-left">
          {open ? <ChevronDownIcon className="mt-1 h-4 w-4 shrink-0" />
                : <ChevronRightIcon className="mt-1 h-4 w-4 shrink-0" />}
          <span className="min-w-0 flex-1">
            <span className="flex flex-wrap items-center gap-2">
              <SeverityBadge severity={rule.severity} />
              <span className="font-medium">{rule.title}</span>
              <OriginTag origin={rule.origin} />
              {rule.status !== "active" && (
                <Badge variant={rule.status === "pending" ? "warning" : "outline"} className="text-[10px]">
                  {t(`admin.reviewRules.status.${rule.status}`)}
                </Badge>
              )}
              {rule.path_glob && (
                <Badge variant="outline" className="font-mono text-[10px]">{rule.path_glob}</Badge>
              )}
              {rule.agents.length > 0 && (
                <span className="text-xs text-[var(--color-muted-foreground)]">
                  {t("admin.reviewRules.onlyFor", { agents: rule.agents.join(", ") })}
                </span>
              )}
            </span>
            {!open && (
              <span className="mt-0.5 line-clamp-1 block text-xs text-[var(--color-muted-foreground)]">
                {rule.instructions}
              </span>
            )}
          </span>
        </button>
        {canEdit && rule.status === "pending" && (
          <div className="flex shrink-0 gap-1">
            <Button size="sm" variant="outline" onClick={() => setStatus.mutate("active")}
                    disabled={setStatus.isPending}>
              <CheckIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.approve")}
            </Button>
            <Button size="sm" variant="ghost" onClick={() => setStatus.mutate("rejected")}
                    disabled={setStatus.isPending}>
              <XIcon className="h-4 w-4 mr-1" /> {t("admin.reviewRules.reject")}
            </Button>
          </div>
        )}
      </div>
      {open && (
        <div className="space-y-3 border-t border-[var(--color-border)] p-3">
          {(rule.rationale || rule.source_ref) && (
            <div className="space-y-1 text-xs text-[var(--color-muted-foreground)]">
              {rule.rationale && <p>{t("admin.reviewRules.rationale", { text: rule.rationale })}</p>}
              {rule.source_ref && (
                <p>{t("admin.reviewRules.source")} <code>{rule.source_ref}</code></p>
              )}
            </div>
          )}
          {canEdit ? (
            <RuleEditor
              initial={rule}
              agents={agents}
              onSave={async (payload) => {
                await reviewRulesApi.update(token!, rule.id, payload);
                onChanged();
                toast.success(t("admin.reviewRules.saved"));
              }}
            />
          ) : (
            <p className="whitespace-pre-wrap text-sm">{rule.instructions}</p>
          )}
        </div>
      )}
    </div>
  );
}


function RuleEditor({
  initial, agents, onSave, onCancel,
}: {
  initial?: ReviewRule;
  agents: string[];
  onSave: (p: ReviewRuleIn) => Promise<void>;
  onCancel?: () => void;
}) {
  const t = useT();
  const [title, setTitle] = useState(initial?.title ?? "");
  const [instructions, setInstructions] = useState(initial?.instructions ?? "");
  const [glob, setGlob] = useState(initial?.path_glob ?? "");
  const [severity, setSeverity] = useState<ReviewRuleSeverity>(initial?.severity ?? "warning");
  const [targets, setTargets] = useState<string[]>(initial?.agents ?? []);
  const [good, setGood] = useState(initial?.examples_good ?? "");
  const [bad, setBad] = useState(initial?.examples_bad ?? "");

  const save = useMutation({
    mutationFn: () => onSave({
      title: title.trim(), instructions: instructions.trim(),
      path_glob: glob.trim() || null, severity, agents: targets,
      examples_good: good.trim() || null, examples_bad: bad.trim() || null,
    }),
    onError: (e) => toast.error(t("admin.reviewRules.saveFailed", { message: (e as Error).message })),
  });

  return (
    <div className="space-y-3">
      <div className="grid gap-3 sm:grid-cols-[1fr_12rem]">
        <div>
          <Label htmlFor={`rr-title-${initial?.id ?? "new"}`}>{t("admin.reviewRules.labelTitle")}</Label>
          <Input id={`rr-title-${initial?.id ?? "new"}`} value={title} maxLength={MAX_TITLE}
                 onChange={(e) => setTitle(e.target.value)}
                 placeholder={t("admin.reviewRules.placeholderTitle")} />
        </div>
        <div>
          <Label>{t("admin.reviewRules.labelSeverity")}</Label>
          <Select className="w-full" value={severity}
                  onChange={(v) => setSeverity(v as ReviewRuleSeverity)}
                  options={SEVERITIES.map((s) => ({ value: s, label: t(`admin.reviewRules.severity.${s}`) }))} />
        </div>
      </div>
      <div>
        <Label>{t("admin.reviewRules.labelInstructions")}</Label>
        <Textarea rows={4} value={instructions} maxLength={MAX_INSTRUCTIONS}
                  onChange={(e) => setInstructions(e.target.value)}
                  placeholder={t("admin.reviewRules.placeholderInstructions")} />
        <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">
          {t("admin.reviewRules.counter", { count: instructions.length, max: MAX_INSTRUCTIONS })}
        </p>
      </div>
      <div>
        <Label>{t("admin.reviewRules.labelGlob")}</Label>
        <Input value={glob} onChange={(e) => setGlob(e.target.value)} placeholder="src/**/*.{ts,tsx}" />
        <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">{t("admin.reviewRules.globHint")}</p>
      </div>
      {agents.length > 0 && (
        <div>
          <Label>{t("admin.reviewRules.labelAgents")}</Label>
          <div className="mt-1 flex flex-wrap gap-3 text-sm">
            {agents.map((a) => (
              <label key={a} className="flex items-center gap-1.5">
                <input
                  type="checkbox"
                  checked={targets.includes(a)}
                  onChange={() => setTargets((prev) =>
                    prev.includes(a) ? prev.filter((x) => x !== a) : [...prev, a])}
                />
                {a}
              </label>
            ))}
          </div>
          <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">{t("admin.reviewRules.agentsHint")}</p>
        </div>
      )}
      <div className="grid gap-3 sm:grid-cols-2">
        <div>
          <Label>{t("admin.reviewRules.labelGood")}</Label>
          <Textarea rows={3} className="font-mono text-xs" value={good} maxLength={MAX_EXAMPLE}
                    onChange={(e) => setGood(e.target.value)} />
        </div>
        <div>
          <Label>{t("admin.reviewRules.labelBad")}</Label>
          <Textarea rows={3} className="font-mono text-xs" value={bad} maxLength={MAX_EXAMPLE}
                    onChange={(e) => setBad(e.target.value)} />
        </div>
      </div>
      <div className="flex justify-end gap-2">
        {onCancel && <Button variant="ghost" onClick={onCancel}>{t("common.cancel")}</Button>}
        <Button onClick={() => save.mutate()}
                disabled={save.isPending || !title.trim() || !instructions.trim()}>
          <SaveIcon className="h-4 w-4 mr-1" />
          {save.isPending ? t("common.saving") : t("common.save")}
        </Button>
      </div>
    </div>
  );
}


function LibraryDialog({
  open, onOpenChange, repo, onAdded,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  repo: string | null;
  onAdded: () => void;
}) {
  const t = useT();
  const token = useToken();
  const [q, setQ] = useState("");
  const [language, setLanguage] = useState("");
  const [picked, setPicked] = useState<Set<string>>(new Set());
  const [status, setStatus] = useState<"active" | "pending">("active");

  const library = useQuery({
    queryKey: ["review-rules-library", repo ?? "", q, language],
    queryFn: () => reviewRulesApi.library(token!, { q, language, repo }),
    enabled: !!token && open,
  });

  const add = useMutation({
    mutationFn: () => reviewRulesApi.addFromLibrary(token!, Array.from(picked), repo, status),
    onSuccess: (r) => {
      toast.success(t("admin.reviewRules.libraryAdded", { count: r.created.length }));
      setPicked(new Set());
      onAdded();
      onOpenChange(false);
    },
    onError: (e) => toast.error(t("admin.reviewRules.saveFailed", { message: (e as Error).message })),
  });

  const flip = (entry: LibraryRule) => setPicked((prev) => {
    const next = new Set(prev);
    if (next.has(entry.id)) next.delete(entry.id);
    else next.add(entry.id);
    return next;
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{t("admin.reviewRules.libraryTitle")}</DialogTitle>
          <DialogDescription>
            {repo
              ? t("admin.reviewRules.libraryDescRepo", { repo })
              : t("admin.reviewRules.libraryDescWorkspace")}
          </DialogDescription>
        </DialogHeader>
        <div className="flex flex-col gap-2 sm:flex-row">
          <Input className="flex-1" value={q} onChange={(e) => setQ(e.target.value)}
                 placeholder={t("admin.reviewRules.librarySearch")} />
          <Select
            className="sm:w-44"
            value={language}
            onChange={setLanguage}
            options={[
              { value: "", label: t("admin.reviewRules.libraryAllLanguages") },
              ...(library.data?.languages ?? []).map((l) => ({ value: l, label: l })),
            ]}
          />
        </div>
        <div className="space-y-2">
          {library.isLoading && (
            <p className="text-sm text-[var(--color-muted-foreground)]">{t("common.loading")}</p>
          )}
          {(library.data?.rules ?? []).map((entry) => (
            <label key={entry.id}
                   className="flex cursor-pointer items-start gap-2 rounded-md border border-[var(--color-border)] p-2 text-sm">
              <input type="checkbox" className="mt-1" disabled={entry.added}
                     checked={entry.added || picked.has(entry.id)} onChange={() => flip(entry)} />
              <span className="min-w-0 flex-1">
                <span className="flex flex-wrap items-center gap-2">
                  <SeverityBadge severity={entry.severity} />
                  <span className="font-medium">{entry.title}</span>
                  {entry.added && (
                    <Badge variant="success" className="text-[10px]">{t("admin.reviewRules.libraryAlready")}</Badge>
                  )}
                </span>
                <span className="mt-0.5 block text-xs text-[var(--color-muted-foreground)]">
                  {entry.instructions}
                </span>
                <span className="mt-1 flex flex-wrap gap-1">
                  {entry.languages.map((l) => (
                    <Badge key={l} variant="outline" className="text-[10px]">{l}</Badge>
                  ))}
                </span>
              </span>
            </label>
          ))}
          {library.data && library.data.rules.length === 0 && (
            <p className="text-sm text-[var(--color-muted-foreground)]">{t("admin.reviewRules.libraryEmpty")}</p>
          )}
        </div>
        <DialogFooter className="flex flex-col gap-2 sm:flex-row sm:items-center">
          <Select
            className="sm:w-48"
            value={status}
            onChange={(v) => setStatus(v as "active" | "pending")}
            options={[
              { value: "active", label: t("admin.reviewRules.libraryAsActive") },
              { value: "pending", label: t("admin.reviewRules.libraryAsPending") },
            ]}
          />
          <Button onClick={() => add.mutate()} disabled={picked.size === 0 || add.isPending}>
            <PlusIcon className="h-4 w-4 mr-1" />
            {t("admin.reviewRules.libraryAdd", { count: picked.size })}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
